# Generated by Django 6.0.2 on 2026-03-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=10)),
                ('modelo_carro', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
            ],
        ),
    ]
