# Generated by Django 6.0.2 on 2026-03-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='categoria',
            field=models.CharField(choices=[('popular', 'Carro Popular'), ('suv', 'SUV'), ('caminhonete', 'Caminhonete')], default='popular', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comissao',
            name='servico',
            field=models.CharField(choices=[('sem_cera', 'Sem cera'), ('com_cera', 'Com cera')], max_length=20),
        ),
    ]
