# Generated by Django 6.0.2 on 2026-03-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comissao_categoria_alter_comissao_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='servico',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='valor_servico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
