# Generated by Django 6.0.2 on 2026-05-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('NEUTRO', 'Neutro')], max_length=20),
        ),
    ]
